-- ============================================================
-- SEED DATA FOR SHARESTEAK MARKETPLACE
-- ============================================================
-- This file adds seed data for development and testing
-- Run this after applying all migrations
-- ============================================================

-- Note: Actual user IDs will be generated by Supabase Auth
-- This seed data creates sample profiles that can be linked after authentication

-- ============================================================
-- SAMPLE CATEGORIES (if using categories table)
-- ============================================================

INSERT INTO public.categories (id, name, description, slug, is_active)
VALUES
  ('c0000000-0000-0000-0000-000000000001', 'Beef', 'Premium beef cuts and products', 'beef', true),
  ('c0000000-0000-0000-0000-000000000002', 'Pork', 'Quality pork products', 'pork', true),
  ('c0000000-0000-0000-0000-000000000003', 'Chicken', 'Fresh chicken and poultry', 'chicken', true),
  ('c0000000-0000-0000-0000-000000000004', 'Lamb', 'Tender lamb cuts', 'lamb', true),
  ('c0000000-0000-0000-0000-000000000005', 'Seafood', 'Fresh and frozen seafood', 'seafood', true),
  ('c0000000-0000-0000-0000-000000000006', 'Game', 'Wild game meats', 'game', true)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- SAMPLE PRODUCTS
-- ============================================================
-- Note: seller_id should reference actual user IDs from auth.users
-- For testing, you'll need to create actual users first

-- Example product structure (uncomment and adjust when you have real seller IDs):
/*
INSERT INTO public.products (
  id, seller_id, category_id, title, description,
  price, unit, inventory, is_active
) VALUES
  (
    'p0000000-0000-0000-0000-000000000001',
    '<seller-user-id>',
    'c0000000-0000-0000-0000-000000000001',
    'Premium Ribeye Steak',
    'USDA Prime ribeye, dry-aged 28 days for maximum flavor',
    45.99,
    'lb',
    100,
    true
  );
*/

-- ============================================================
-- ENABLE RLS ON ALL TABLES
-- ============================================================

-- Re-enable RLS if it was disabled for seeding
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN (
        SELECT tablename
        FROM pg_tables
        WHERE schemaname = 'public'
        AND tablename NOT LIKE 'pg_%'
    ) LOOP
        EXECUTE 'ALTER TABLE public.' || quote_ident(r.tablename) || ' ENABLE ROW LEVEL SECURITY';
    END LOOP;
END $$;

-- Seed data complete!
-- Remember to create actual users through Supabase Auth before using the application
